apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: main-triggertemplate
spec:
  resourcetemplates:
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineRun
    metadata:
      name: main-pipelinerun-$(uid)
    spec:
      pipelineRef:
        name: main-pipeline
      serviceAccountNames:
        - taskName: build-mq
          serviceAccountName: cicd-mq-sa
        - taskName: deploy-wait-mq
          serviceAccountName: cicd-mq-sa
        - taskName: build-ace-int-server-ace-api
          serviceAccountName: cicd-ace-sa
        - taskName: build-ace-int-server-ace-bernie
          serviceAccountName: cicd-ace-sa
        - taskName: build-ace-int-server-ace-acme
          serviceAccountName: cicd-ace-sa
        - taskName: build-ace-int-server-ace-chris
          serviceAccountName: cicd-ace-sa
        - taskName: deploy-wait-ace-api
          serviceAccountName: cicd-ace-sa
        - taskName: deploy-wait-ace-chris
          serviceAccountName: cicd-ace-sa
        - taskName: deploy-wait-ace-acme
          serviceAccountName: cicd-ace-sa
        - taskName: deploy-wait-ace-bernie
          serviceAccountName: cicd-ace-sa
        - taskName: dev-e2e
          serviceAccountName: cicd-test
        - taskName: image-push-to-test-ace-chris
          serviceAccountName: cicd-push-to-test
        - taskName: image-push-to-test-ace-acme
          serviceAccountName: cicd-push-to-test
        - taskName: image-push-to-test-ace-bernie
          serviceAccountName: cicd-push-to-test
        - taskName: image-push-to-test-ace-api
          serviceAccountName: cicd-push-to-test
        - taskName: image-push-to-test-mq
          serviceAccountName: cicd-push-to-test
        # - taskName: cicd-test-pipeline-script-run
        #   serviceAccountName: cicd-deploy-to-test
      resources:
      - name: git-source
        resourceRef:
          name: git-source
      params:
      - name: imageTag
        value: $(uid)
