apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: dev-triggertemplate
spec:
  resourcetemplates:
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineRun
    metadata:
      name: dev-pipelinerun-$(uid)
    spec:
      pipelineRef:
        name: dev-pipeline
      serviceAccountNames:
        - taskName: build-mq
          serviceAccountName: cicd-mq-sa
        - taskName: deploy-wait-mq
          serviceAccountName: cicd-mq-sa
        - taskName: build-ace-int-server-ace-api
          serviceAccountName: cicd-ace-sa
        - taskName: build-ace-int-server-ace-bernie
          serviceAccountName: cicd-ace-sa
        - taskName: build-ace-int-server-ace-acme
          serviceAccountName: cicd-ace-sa
        - taskName: build-ace-int-server-ace-chris
          serviceAccountName: cicd-ace-sa
        - taskName: deploy-wait-ace-api
          serviceAccountName: cicd-ace-sa
        - taskName: deploy-wait-ace-chris
          serviceAccountName: cicd-ace-sa
        - taskName: deploy-wait-ace-acme
          serviceAccountName: cicd-ace-sa
        - taskName: deploy-wait-ace-bernie
          serviceAccountName: cicd-ace-sa
      resources:
      - name: git-source
        resourceRef:
          name: git-source
      params:
      - name: imageTag
        value: $(uid)
