kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tekton-triggers-role
rules:
# Permissions for every EventListener deployment to function
- apiGroups: ["triggers.tekton.dev"]
  resources: ["eventlisteners", "triggerbindings", "triggertemplates"]
  verbs: ["get"]
- apiGroups: [""]
# secrets are only needed for Github/Gitlab interceptors, serviceaccounts only for per trigger authorization
  resources: ["configmaps", "secrets", "serviceaccounts"]
  verbs: ["get", "list", "watch"]
# Permissions to create resources in associated TriggerTemplates
- apiGroups: ["tekton.dev"]
  resources: ["pipelineruns", "pipelineresources", "taskruns"]
  verbs: ["create"]
---

# Ace Integration Service account configuration
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ace-int-srv-role
rules:
# Permissions for appconnect integration server
- apiGroups: ["appconnect.ibm.com"]
  resources: ["designerauthorings", "dashboards", "switchservers", "configurations", "integrationservers"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
# Permission to get pods
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "get"]


---

# MQ Service account configuration
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mq-qm-role
rules:
# Permissions for MQ
- apiGroups: ["mq.ibm.com"]
  resources: ["queuemanagers", "queuemanagers/finalizers", "queuemanagers/status"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
# Permission to get pods during deploy stage
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "get"]

---

# Role for the test task to get routes in dev namespace
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-test-routes
rules:
# Permissions for test task to list routes in dev namespace
- apiGroups: ["route.openshift.io"]
  resources: ["routes"]
  verbs: ["list"]

---

# Role for the test task in postgres namespace
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-postgres-test-task
  namespace: postgres
rules:
# Permissions for test task to list, get and create pods in postgres namespace
- apiGroups: [""]
  resources: ["pods", "pods/exec"]
  verbs: ["list", "get", "create"]

---

# Deploy to test namespace permissions
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-deploy-test
rules:
# Permission to get tasks, pipelines in tekton.dev in dev namespace - to apply pipeline and task yamls
- apiGroups: ["tekton.dev"]
  resources: ["pipelines", "tasks"]
  verbs: ["get", "create", "patch"]