apiVersion: integration.ibm.com/v1beta1
kind: Demo
metadata:
  name: demos
  namespace: cp4i
spec:
  # Not sure what this would be used for!
  version: 2020.3.1

  general:
    storage:
      block:
        class: cp4i-block-performance
      file:
        class: ibmc-file-gold-gid
    # Include this? Maybe when we turn this into an operator the samples repo would
    # be baked in as a locally running image, so can work with airgap.
    samplesRepoBranch: main

  demos:
    all:
      enabled: true
    cognitiveCarRepair:
      enabled: true
    drivewayDentDeletion:
      enabled: true
    eventEnabledInsurance:
      enabled: true

  # Allow products to be enabled independently. Enabling a demo will automatically
  # enable required products.
  products:
    - type: aceDashboard
      enabled: true
    - type: aceDashboard
      enabled: false
      namespaceSuffix: -ddd-test
    - type: aceDesigner
      enabled: true
    - type: apic
      enabled: true
      emailAddress: "your@email.address"
      mailServerHost: "smtp.mailtrap.io"
      mailServerPort: 2525
      mailServerUsername: "<your-username>"
      mailServerPassword: "<your-password>"
    - type: assetRepo
      enabled: true
    - type: eventStreams
      enabled: true
    - type: mq
      enabled: true
    - type: navigator
      enabled: true
      namespaceSuffix: -ddd-test
    - type: tracing
      enabled: true

  # Allow additional addon applications to be enabled independently. Enabling a
  # demo will automatically enable required addons.
  addons:
    # Installs to the postgres namespace
    - type: postgres
      enabled: true
    # Installs to the elasticsearch namespace
    - type: elasticSearch
      enabled: true
    # Installs the pipelines operator cluster scoped
    - type: ocpPipelines
      enabled: true
status:
  version: 2020.3.1
  conditions: []
  phase: Ready
  demos:
    cognitiveCarRepair:
      enabled: true
    drivewayDentDeletion:
      enabled: true
      testNamespace: cp4i-ddd-test
    eventEnabledInsurance:
      enabled: true
  products:
    - type: aceDashboard
      namespace: cp4i
      name: ace-dashboard-demo
    - type: aceDashboard
      namespace: cp4i-ddd-test
      name: ace-dashboard-demo
    - type: aceDesigner
      namespace: cp4i
      name: ace-designer-demo
    - type: apic
      namespace: cp4i
      name: ademo
    - type: assetRepo
      namespace: cp4i
      name: ar-demo
    - type: eventStreams
      namespace: cp4i
      name: es-demo
    - type: mq
      namespace: cp4i
      name: mq-demo
    - type: navigator
      namespace: cp4i
      name: cp4i-navigator
    - type: navigator
      namespace: cp4i-ddd-test
      name: cp4i-ddd-test-navigator
    - type: tracing
      namespace: cp4i
      name: tracing-demo
  addons:
    - type: postgres
      namespace: postgres
    - type: elasticSearch
      namespace: elasticsearch
    - type: ocpPipelines
  namespaces:
    - name: cp4i
    - name: cp4i-ddd-test
