apiVersion: integration.ibm.com/v1beta1
kind: Demo
metadata:
  name: demos
  namespace: cp4i
spec:
  # Not sure what this would be used for!
  version: 2020.3.1

  general:
    storage:
      block:
        class: cp4i-block-performance
      file:
        class: ibmc-file-gold-gid
    # Include this? Maybe when we turn this into an operator the samples repo would
    # be baked in as a locally running image, so can work with airgap.
    samplesRepoBranch: main

  demos:
    all:
      enabled: true
    cognitiveCarRepair:
      enabled: true
    drivewayDentDeletion:
      enabled: true
    eventEnabledInsurance:
      enabled: true
    mappingAssist:
      enabled: true
    weatherChatbot:
      enabled: true

  # Allow products to be enabled independently. Enabling a demo will automatically
  # enable required products.
  products:
    - type: aceDashboard
      enabled: true
    - type: aceDesigner
      enabled: true
    - type: apic
      enabled: true
      emailAddress: "your@email.address"
      mailServerHost: "smtp.mailtrap.io"
      mailServerPort: 2525
      mailServerUsername: "<your-username>"
      mailServerPassword: "<your-password>"
    - type: assetRepo
      enabled: true
    - type: eventStreams
      enabled: true
    - type: mq
      enabled: true
    - type: tracing
      enabled: true

  # Allow additional addon applications to be enabled independently. Enabling a
  # demo will automatically enable required addons.
  addons:
    - type: postgres
      enabled: true
    - type: elasticSearch
      enabled: true
    - type: ocpPipelines
      enabled: true
status:
  addons:
    - type: postgres
      installed: true
      readyToUse: true
    - type: elasticSearch
      installed: true
      readyToUse: true
    - type: ocpPipelines
      installed: true
      readyToUse: true
  conditions: []
  demos:
    - mappingAssist:
      enabled: true
    - weatherChatbot:
      enabled: true
  namespaces:
    - name: cp4i
  phase: Pending
  products:
    - name: ace-dashboard-demo
      type: aceDashboard
      installed: true
      readyToUse: true
      namespace: cp4i
    - name: ace-designer-demo
      type: aceDesigner
      installed: true
      readyToUse: true
      namespace: cp4i
    - name: ademo
      type: apic
      installed: true
      readyToUse: true
      namespace: cp4i
    - name: ar-demo
      type: assetRepo
      installed: true
      readyToUse: true
      namespace: cp4i
    - name: es-demo
      type: eventStreams
      installed: true
      readyToUse: true
      namespace: cp4i
    - name: mq-demo
      type: mq
      installed: true
      readyToUse: true
      namespace: cp4i
    - name: cp4i-navigator
      type: navigator
      installed: true
      readyToUse: true
      namespace: cp4i
    - name: tracing-demo
      type: tracing
      installed: true
      readyToUse: true
      namespace: cp4i
  version: 2020.3.1-1
