apiVersion: v1
kind: ServiceAccount
metadata:
  name: cicd-ace-sa
secrets:
  - name: cicd-ace

---

apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: git-source
  namespace: driveway-dent-deletion
spec:
  type: git
  params:
    - name: revision
      value: dent-deletion
    - name: url
      value: https://github.com/IBM/cp4i-deployment-samples.git

---

apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-push-docker-image
  namespace: driveway-dent-deletion
spec:
  resources:
    inputs:
      - name: git-source
        type: git
  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:latest
      env:
        - name: "DOCKER_CONFIG"
          value: "/tekton/home/.docker/"
      command:
        - /kaniko/executor
      args:
        - --dockerfile=/workspace/git-source/DrivewayDentDeletion/DOCKERFILE
        - --destination=image-registry.openshift-image-registry.svc:5000/ace/ace2:latest
        - --context=/workspace/git-source/DrivewayDentDeletion/
        - --verbosity=debug
        - --log-timestamp
        - --insecure-registry=image-registry.openshift-image-registry.svc:5000/ace/ace2:latest
        - --skip-tls-verify
      securityContext:
        runAsUser: 0

---

apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: ace-pipeline
  namespace: driveway-dent-deletion
spec:
  resources:
    - name: git-source
      type: git
  tasks:
    - name: ace-run
      taskRef:
        name: build-push-docker-image
      resources:
        inputs:
          - name: git-source
            resource: git-source

---

apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: ace-cicd-triggertemplate
spec:
  params:
  - name: git-repo-name
    description: The name of the deployment to be created / patched
  resourcetemplates:
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineRun
    metadata:
      name: cicd-$(params.git-repo-name)-pipelinerun-$(uid)
      namespace: driveway-dent-deletion
    spec:
      pipelineRef:
        name: ace-pipeline
      serviceAccountName: cicd-ace-sa
      resources:
      - name: git-source
        resourceRef:
          name: git-source

---

apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: ace-cicd-triggerbinding
  namespace: driveway-dent-deletion
spec:
  params:
  - name: git-repo-name
    value: cp4i-deployment-samples

---

apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: ace-cicd-trigger
  namespace: driveway-dent-deletion
spec:
  serviceAccountName: cicd-ace-sa
  triggers:
  - bindings:
    - name: ace-cicd-triggerbinding
    template:
      name: ace-cicd-triggertemplate

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tekton-triggers-role
  namespace: driveway-dent-deletion
rules:
- apiGroups: [""]
  resources: ["pods", "configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups:
  - triggers.tekton.dev
  resources:
  - eventlisteners
  - triggerbindings
  - triggertemplates
  - pipelineresources
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - tekton.dev
  resources:
  - pipelines
  - tasks
  - pipelineruns
  - pipelineresources
  - secrets
  verbs:
  - create
  - get
  - list
  - watch

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-triggers-rolebinding
  namespace: driveway-dent-deletion
subjects:
- kind: ServiceAccount
  name: cicd-ace-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tekton-triggers-role
