apiVersion: v1
kind: ServiceAccount
metadata:
  name: cicd-el

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: cicd-ace-sa
secrets:
  - name: cicd-ace
imagePullSecrets:
  - name: ibm-entitlement-key

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: cicd-mq-sa
secrets:
  - name: cicd-mq
imagePullSecrets:
  - name: ibm-entitlement-key

---

apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: git-source
spec:
  type: git
  params:
    - name: revision
      value: dent-deletion
    - name: url
      value: https://github.com/IBM/cp4i-deployment-samples.git

---

apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-push-ace-api-docker-image
spec:
  resources:
    inputs:
      - name: git-source
        type: git
  steps:
    - name: build-and-push-ace
      image: gcr.io/kaniko-project/executor:latest
      env:
        - name: "DOCKER_CONFIG"
          value: "/tekton/home/.docker/"
      command:
        - /kaniko/executor
      args:
        - --context=/workspace/git-source/DrivewayDentDeletion/ace-api
        - --dockerfile=/workspace/git-source/DrivewayDentDeletion/ace-api/Dockerfile
        - --destination=image-registry.openshift-image-registry.svc:5000/ace/ace1:latest
        - --verbosity=debug
        - --log-timestamp
        - --skip-tls-verify
      securityContext:
        runAsUser: 0

---

apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-push-mq-api-docker-image
spec:
  resources:
    inputs:
      - name: git-source
        type: git
  steps:
    - name: build-and-push-mq
      image: gcr.io/kaniko-project/executor:latest
      env:
        - name: "DOCKER_CONFIG"
          value: "/tekton/home/.docker/"
      command:
        - /kaniko/executor
      args:
        - --context=/workspace/git-source/DrivewayDentDeletion/ace-api
        - --dockerfile=/workspace/git-source/DrivewayDentDeletion/ace-api/Dockerfile
        - --destination=image-registry.openshift-image-registry.svc:5000/mq/mq1:latest
        - --verbosity=debug
        - --log-timestamp
        - --skip-tls-verify
      securityContext:
        runAsUser: 0

---

apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: main-pipeline
spec:
  resources:
    - name: git-source
      type: git
  tasks:
    - name: ace-api-run
      taskRef:
        name: build-push-ace-api-docker-image
      resources:
        inputs:
          - name: git-source
            resource: git-source
    - name: mq-api-run
      taskRef:
        name: build-push-mq-api-docker-image
      resources:
        inputs:
          - name: git-source
            resource: git-source

---

apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: main-triggertemplate
spec:
  resourcetemplates:
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineRun
    metadata:
      name: main-pipelinerun-$(uid)
    spec:
      pipelineRef:
        name: main-pipeline
      serviceAccountNames:
        - taskName: ace-api-run
          serviceAccountName: cicd-ace-sa
        - taskName: mq-api-run
          serviceAccountName: cicd-mq-sa
      resources:
      - name: git-source
        resourceRef:
          name: git-source

---

apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: main-trigger
spec:
  serviceAccountName: cicd-el
  triggers:
  - template:
      name: main-triggertemplate

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tekton-triggers-role
rules:
# Permissions for every EventListener deployment to function
- apiGroups: ["triggers.tekton.dev"]
  resources: ["eventlisteners", "triggerbindings", "triggertemplates"]
  verbs: ["get"]
- apiGroups: [""]
  # secrets are only needed for Github/Gitlab interceptors, serviceaccounts only for per trigger authorization
  resources: ["configmaps", "secrets", "serviceaccounts"]
  verbs: ["get", "list", "watch"]
# Permissions to create resources in associated TriggerTemplates
- apiGroups: ["tekton.dev"]
  resources: ["pipelineruns", "pipelineresources", "taskruns"]
  verbs: ["create"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-triggers-rolebinding
subjects:
- kind: ServiceAccount
  name: cicd-el
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tekton-triggers-role
