apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: eei-simulator-pipeline
spec:
  workspaces:
    - name: git-source
  tasks:
    - name: clone-git-source
      taskRef:
        name: git-clone
        kind: ClusterTask
      params:
        - name: url
          value: "{{FORKED_REPO}}"
        - name: subdirectory
          value: ""
        - name: deleteExisting
          value: "true"
        - name: revision
          value: "{{BRANCH}}"
      workspaces:
        - name: output
          workspace: git-source

    # Build the quote lifecycle simulator app image
    - name: build-simulator-image
      runAfter:
        - clone-git-source
      taskSpec:
        workspaces:
          - name: output
        steps:
          - name: build
            image: quay.io/buildah/stable:latest
            securityContext:
              privileged: true
            script: |
              buildah --storage-driver vfs bud \
                -f /workspace/git-source/EventEnabledInsurance/QuoteLifecycleSimulator/Simulator.Dockerfile \
                -t image-registry.openshift-image-registry.svc:5000/{{NAMESPACE}}/quote-simulator-eei:latest \
                /workspace/git-source/EventEnabledInsurance/QuoteLifecycleSimulator
              buildah --storage-driver vfs push \
                --tls-verify=false \
                image-registry.openshift-image-registry.svc:5000/{{NAMESPACE}}/quote-simulator-eei:latest

    # Deploy the quote lifecycle simulator app image
    - name: deploy-simulator-app
      runAfter:
        - build-simulator-image
      taskSpec:
        workspaces:
          - name: git-source
        steps:
          - name: oc
            image: quay.io/openshift/origin-cli:latest
            script: "/workspace/git-source/EventEnabledInsurance/QuoteLifecycleSimulator/deploy-simulator.sh -n {{NAMESPACE}} -t 1000 -m 10"
