# Role for the test task in postgres namespace
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-create-deployments-eei
rules:
# Permissions for test task to list, get and create pods and configmaps in postgres namespace
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "create", "patch"]
