apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: git-workspace-eei
spec:
  storageClassName: ibmc-file-gold-gid
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
